/**
 * Classic chat endpoints (extracted verbatim from the original server.ts):
 *   POST /api/chat/stream   — SSE streaming chat (v1 protocol, kept stable)
 *   POST /api/chat/title    — conversation title generation
 *   POST /api/memory/extract — long-term memory extraction
 *   POST /api/tts           — Gemini neural TTS
 */

import { Router, Request, Response } from 'express';
import { Type } from '@google/genai';
import { aiBrain } from '../../src/core/ai';
import { modelRouter } from '../../src/core/ai/router';
import {
  buildJennaSystemPrompt,
  extractHeuristicTitle,
  optimizeConversationContext,
} from '../../src/core/promptBuilder';
import { redactSecrets } from '../middleware/redact';

export function createChatRouter(): Router {
  const router = Router();

  // Stream Gemini Chat completion
  router.post('/chat/stream', async (req: Request, res: Response) => {
    try {
      const {
        messages = [],
        systemInstruction = '',
        injectedMemories = [],
        userProfile = {},
        model = 'auto',
        temperature = 0.7,
      } = req.body;

      const apiKey = process.env.GEMINI_API_KEY;
      if (!apiKey) {
        res.status(500).json({
          error: 'GEMINI_API_KEY is missing. Please configure your API key in Settings > Secrets.',
        });
        return;
      }

      // Prepare system instructions with refined Jenna Persona and Memory Injection
      const fullSystemPrompt = buildJennaSystemPrompt({
        userProfile,
        injectedMemories,
        systemInstruction,
      });

      // Clean and validate dialogue turns for Google Gen AI SDK
      const rawTurns: Array<{ role: 'user' | 'model'; content: string }> = [];
      for (const msg of messages) {
        if (!msg || typeof msg.content !== 'string' || !msg.content.trim()) continue;
        const role: 'user' | 'model' = msg.role === 'user' ? 'user' : 'model';
        // Merge consecutive messages from same role
        if (rawTurns.length > 0 && rawTurns[rawTurns.length - 1].role === role) {
          rawTurns[rawTurns.length - 1].content += `\n\n${msg.content.trim()}`;
        } else {
          rawTurns.push({ role, content: msg.content.trim() });
        }
      }

      // Ensure contents begin with user turn
      if (rawTurns.length > 0 && rawTurns[0].role !== 'user') {
        rawTurns.shift();
      }

      if (rawTurns.length === 0) {
        res.status(400).json({ error: 'No valid message content provided.' });
        return;
      }

      // Apply intelligent context window sliding and token budget management
      const validTurns = optimizeConversationContext(rawTurns, {
        maxTurns: 30,
        maxEstimatedTokens: 24000,
      });

      // Setup SSE headers with unbuffered options for nginx / proxy
      res.setHeader('Content-Type', 'text/event-stream; charset=utf-8');
      res.setHeader('Cache-Control', 'no-cache, no-transform');
      res.setHeader('Connection', 'keep-alive');
      res.setHeader('X-Accel-Buffering', 'no');
      res.flushHeaders?.();

      // Route the model via ModelRouter ('auto' or explicit user selection).
      const route = modelRouter.resolve('fast_chat', typeof model === 'string' ? model : 'auto');
      const isClientDisconnected = () => {
        if (req.destroyed || res.writableEnded) return true;
        return res.socket ? !res.socket.writable : false;
      };

      const { modelUsed, tokensEmitted } = await aiBrain.streamChat(
        route.modelId,
        validTurns,
        {
          systemInstruction: fullSystemPrompt,
          temperature: Number(temperature) || 0.7,
          onToken: (token: string) => {
            if (!isClientDisconnected()) {
              res.write(`data: ${JSON.stringify({ type: 'token', token })}\n\n`);
              (res as any).flush?.();
            }
          },
          isAborted: isClientDisconnected,
        }
      );

      if (tokensEmitted === 0 && !isClientDisconnected()) {
        res.write(
          `data: ${JSON.stringify({ type: 'error', error: 'No response was generated by Jenna. Please retry.' })}\n\n`
        );
        res.end();
        return;
      }

      if (!isClientDisconnected()) {
        res.write(`data: ${JSON.stringify({ type: 'done', model: modelUsed })}\n\n`);
        (res as any).flush?.();
        res.end();
      }
    } catch (error: any) {
      console.error('[Jenna API] Stream error:', redactSecrets(error?.message || String(error)));
      let errorMessage = error?.message || 'Failed to generate response from Jenna.';
      if (error?.isRetryable) {
        errorMessage =
          'Jenna is currently experiencing high demand. Please retry in a moment.';
      }

      // Scrub any sensitive credential patterns
      errorMessage = redactSecrets(errorMessage);

      // Check if headers have already been sent for SSE
      if (res.headersSent) {
        if (!req.destroyed && !res.writableEnded) {
          res.write(`data: ${JSON.stringify({ type: 'error', error: errorMessage })}\n\n`);
          (res as any).flush?.();
          res.end();
        }
      } else {
        res.status(error?.statusCode || 500).json({ error: errorMessage });
      }
    }
  });

  // Fast & Resilient Conversation Title Generator
  router.post('/chat/title', async (req: Request, res: Response) => {
    try {
      const { firstMessage } = req.body;
      if (!firstMessage) {
        res.json({ title: 'New Conversation' });
        return;
      }

      const fallbackTitle = extractHeuristicTitle(firstMessage);

      try {
        const route = modelRouter.resolve('title_gen');
        const { text } = await aiBrain.generateText(
          route.modelId,
          [
            {
              role: 'user',
              content: `Create a concise, descriptive title (3-5 words maximum, no quotes, no punctuation at the end) for a chat that begins with this user message:\n"${firstMessage.slice(0, 300)}"`,
            },
          ],
          {
            systemInstruction: 'You are a concise title generator. Respond only with the title.',
            temperature: 0.2,
          }
        );

        const title = text?.trim().replace(/^["']|["']$/g, '') || fallbackTitle;
        res.json({ title: title.slice(0, 50) });
      } catch {
        // Fallback gracefully without throwing or warning loudly
        res.json({ title: fallbackTitle });
      }
    } catch (err: any) {
      res.json({ title: 'New Conversation' });
    }
  });

  // Extract Long-Term Memories from conversation snippet
  router.post('/memory/extract', async (req: Request, res: Response) => {
    try {
      const { messages = [] } = req.body;
      if (messages.length === 0) {
        res.json({ memories: [] });
        return;
      }

      const transcript = messages
        .slice(-6)
        .map((m: { role: string; content: string }) => `${m.role.toUpperCase()}: ${m.content}`)
        .join('\n');

      const prompt = `Analyze this conversation snippet and extract any notable personal facts, user preferences, explicit instructions/directives, work context, or goals that Jenna should remember for future sessions.
Do NOT extract transient questions, conversational greetings, or trivial banter.
Snippet:
${transcript}`;

      try {
        const route = modelRouter.resolve('summarize_cheap');
        const { text } = await aiBrain.generateText(
          route.modelId,
          [{ role: 'user', content: prompt }],
          {
            systemInstruction: 'You extract durable user facts and preferences for long-term AI memory.',
            responseMimeType: 'application/json',
            responseSchema: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  category: {
                    type: Type.STRING,
                    description:
                      'One of: personal_facts, preferences, directives, projects_and_goals, work_context',
                  },
                  content: {
                    type: Type.STRING,
                    description:
                      'A clear, standalone statement about the user in third person (e.g. "User prefers TypeScript over JavaScript")',
                  },
                  confidence: {
                    type: Type.NUMBER,
                    description: 'Confidence score from 0.0 to 1.0',
                  },
                },
                required: ['category', 'content', 'confidence'],
              },
            },
          }
        );

        const jsonText = text?.trim() || '[]';
        let rawMemories = [];
        try {
          rawMemories = JSON.parse(jsonText);
        } catch {
          rawMemories = [];
        }

        const memories = Array.isArray(rawMemories)
          ? rawMemories.map((m) => ({
              category: m.category || 'preferences',
              content: m.content || m.fact || '',
              fact: m.content || m.fact || '',
              confidence: m.confidence || 0.9,
            }))
          : [];

        res.json({ memories });
      } catch (err) {
        console.log('[Jenna API] Memory extraction fallback:', err);
        res.json({ memories: [] });
      }
    } catch (err: any) {
      console.error('[Jenna API] Memory extraction error:', err);
      res.json({ memories: [] });
    }
  });

  // Gemini High-Definition TTS Endpoint
  router.post('/tts', async (req: Request, res: Response) => {
    try {
      const { text, voice = 'Kore' } = req.body;
      if (!text || typeof text !== 'string') {
        res.status(400).json({ error: 'Text parameter is required.' });
        return;
      }

      const validVoice = ['Kore', 'Zephyr', 'Puck', 'Fenrir', 'Charon'].includes(voice) ? voice : 'Kore';

      try {
        const speech = await aiBrain.generateSpeech(text, validVoice);
        res.json({
          audio: speech.audioBase64,
          mimeType: speech.mimeType,
          voice: speech.voice,
          text: text.slice(0, 1000),
        });
      } catch (ttsErr: any) {
        res.json({ fallback: true, error: ttsErr?.message || 'Neural TTS fallback' });
      }
    } catch (err: any) {
      console.error('[Jenna API] TTS Error:', err);
      res.json({ fallback: true, error: 'TTS generation failed' });
    }
  });

  return router;
}
